build: fix meson sandbox violation when using wayland-protocols as subproject
When a dependency path is converted to string and dependency is a
subproject, then accessing such file fails in meson with:

    ERROR: Sandbox violation: Tried to grab file ... from a nested subproject.

Use '/' operator as documented in
https://mesonbuild.com/Dependencies.html#dependencies-that-provide-resource-files

Fixes: #715
Signed-off-by: Vasyl Vavrychuk <vvavrychuk@gmail.com>